version: "2"

services:

  php:
    image: skilldlabs/${PHP_IMAGE} # Allowed: 7.0, 5.6.
    container_name: "${COMPOSE_PROJECT_NAME}_php"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    volumes:
      - ../../build:/var/www/html
      - ../${PROFILE_NAME}:/var/www/html/profiles/${PROFILE_NAME}
    networks:
      - front

  adminer:
    image: dockette/adminer:mysql-php7
    container_name: "${COMPOSE_PROJECT_NAME}_adminer"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    networks:
      - front

  mailhog:
    image: mailhog/mailhog
    container_name: "${COMPOSE_PROJECT_NAME}_mail"
    restart: always
    networks:
      - front

  nginx:
    image: wodby/drupal-nginx
    container_name: "${COMPOSE_PROJECT_NAME}_web"
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
#      NGINX_DOCROOT: public # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
    links:
      - mysql:mysql
    depends_on:
      - php
    volumes_from:
      - php
#    volumes:
# Replace nginx config with our values
#      - ./src/docker/nginx/drupal8.conf:/opt/drupal8.conf
# Add keys for ssl if needed
#     - ./src/docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - front

  mysql:
    image: percona:5.7
    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
    volumes:
      - /dev/shm/${COMPOSE_PROJECT_NAME}_mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: d8
      MYSQL_USER: d8
      MYSQL_PASSWORD: d8
      MYSQL_ROOT_PASSWORD: d8root
    restart: always
    networks:
      - front

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${IPRANGE}"
